language: ruby
sudo: false
addons:
  apt:
    packages:
    - bind9
rvm:
  - 2.0.0
  - 2.1.8
  - 2.2.4
  - 2.3.0
  - rbx-2
  - ruby-head
  - jruby-head
matrix:
  allow_failures:
    - rvm: rbx-2 
    - rvm: ruby-head
    - rvm: jruby-head
env: COVERAGE=false
